[2024-12-18T19:28:33.908+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T19:28:33.951+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-18T19:27:12.612495+00:00 [queued]>
[2024-12-18T19:28:33.985+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-18T19:27:12.612495+00:00 [queued]>
[2024-12-18T19:28:33.989+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-18T19:28:34.031+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dashboard> on 2024-12-18 19:27:12.612495+00:00
[2024-12-18T19:28:34.074+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=153) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T19:28:34.087+0000] {standard_task_runner.py:72} INFO - Started process 166 to run task
[2024-12-18T19:28:34.089+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'run_dashboard', 'manual__2024-12-18T19:27:12.612495+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmp5v9opq0t']
[2024-12-18T19:28:34.108+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask run_dashboard
[2024-12-18T19:28:34.471+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-18T19:27:12.612495+00:00 [running]> on host 3053742118dc
[2024-12-18T19:28:34.812+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering_team' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T19:27:12.612495+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-18T19:27:12.612495+00:00'
[2024-12-18T19:28:34.816+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T19:28:37.723+0000] {logging_mixin.py:190} INFO - Dash is running on http://0.0.0.0:8050/
[2024-12-18T19:28:37.723+0000] {dash.py:2160} INFO - Dash is running on http://0.0.0.0:8050/

[2024-12-18T19:28:37.762+0000] {logging_mixin.py:190} INFO -  * Serving Flask app 'fintech_dashboard'
[2024-12-18T19:28:37.764+0000] {logging_mixin.py:190} INFO -  * Debug mode: off
[2024-12-18T19:28:37.768+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8050
 * Running on http://172.19.0.5:8050
[2024-12-18T19:28:37.770+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2024-12-18T21:14:00.035+0000] {job.py:229} INFO - Heartbeat recovered after 1092.58 seconds
[2024-12-18T21:14:45.821+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2024-12-18T21:14:45.824+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-18T21:14:45.830+0000] {process_utils.py:132} INFO - Sending 15 to group 166. PIDs of all processes in the group: [166]
[2024-12-18T21:14:45.832+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 166
[2024-12-18T21:14:45.841+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-18T21:14:45.953+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fintech_dashboard.py", line 164, in create_dashboard
    app.run_server(host="0.0.0.0", port=8050)
  File "/home/airflow/.local/lib/python3.12/site-packages/dash/dash.py", line 2287, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/dash/dash.py", line 2183, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 1191, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/serving.py", line 1069, in run_simple
    srv.serve_forever()
  File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/serving.py", line 766, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/local/lib/python3.12/socketserver.py", line 235, in serve_forever
    ready = selector.select(poll_interval)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-18T21:14:45.991+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fintech_etl_pipeline, task_id=run_dashboard, run_id=manual__2024-12-18T19:27:12.612495+00:00, execution_date=20241218T192712, start_date=20241218T192833, end_date=20241218T211445
[2024-12-18T21:14:46.040+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T21:14:46.088+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=166, status='terminated', exitcode=2, started='19:28:33') (166) terminated with exit code 2
