[2024-12-18T19:30:36.399+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T19:30:36.426+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-18T19:03:40.174077+00:00 [queued]>
[2024-12-18T19:30:36.439+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-18T19:03:40.174077+00:00 [queued]>
[2024-12-18T19:30:36.441+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-18T19:30:36.464+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dashboard> on 2024-12-18 19:03:40.174077+00:00
[2024-12-18T19:30:36.477+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=190) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T19:30:36.481+0000] {standard_task_runner.py:72} INFO - Started process 203 to run task
[2024-12-18T19:30:36.480+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'run_dashboard', 'manual__2024-12-18T19:03:40.174077+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmpc_msafjf']
[2024-12-18T19:30:36.484+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask run_dashboard
[2024-12-18T19:30:36.555+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-18T19:03:40.174077+00:00 [running]> on host 3053742118dc
[2024-12-18T19:30:36.699+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering_team' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T19:03:40.174077+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-18T19:03:40.174077+00:00'
[2024-12-18T19:30:36.702+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T19:30:38.244+0000] {logging_mixin.py:190} INFO - Dash is running on http://0.0.0.0:8050/
[2024-12-18T19:30:38.244+0000] {dash.py:2160} INFO - Dash is running on http://0.0.0.0:8050/

[2024-12-18T19:30:38.253+0000] {logging_mixin.py:190} INFO -  * Serving Flask app 'fintech_dashboard'
[2024-12-18T19:30:38.254+0000] {logging_mixin.py:190} INFO -  * Debug mode: off
[2024-12-18T19:30:38.255+0000] {logging_mixin.py:190} WARNING - Address already in use
[2024-12-18T19:30:38.256+0000] {logging_mixin.py:190} WARNING - Port 8050 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2024-12-18T19:30:38.258+0000] {taskinstance.py:3313} ERROR - Task failed due to SystemExit(1)
[2024-12-18T19:30:38.268+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=fintech_etl_pipeline, task_id=run_dashboard, run_id=manual__2024-12-18T19:03:40.174077+00:00, execution_date=20241218T190340, start_date=20241218T193036, end_date=20241218T193038
[2024-12-18T19:30:38.292+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T19:30:38.297+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 23 for task run_dashboard (Task failed due to SystemExit(1); 203)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/serving.py", line 710, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fintech_dashboard.py", line 164, in create_dashboard
    app.run_server(host="0.0.0.0", port=8050)
  File "/home/airflow/.local/lib/python3.12/site-packages/dash/dash.py", line 2287, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/dash/dash.py", line 2183, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.12/site-packages/flask/app.py", line 1191, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/serving.py", line 1037, in run_simple
    srv = make_server(
          ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/serving.py", line 877, in make_server
    return ThreadedWSGIServer(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/werkzeug/serving.py", line 733, in __init__
    sys.exit(1)
  File "/home/airflow/.local/lib/python3.12/site-packages/billiard/pool.py", line 283, in exit
    return _exit(status)
           ^^^^^^^^^^^^^
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 334, in _run_raw_task
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Task failed due to SystemExit(1)
[2024-12-18T19:30:38.391+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-18T19:30:38.422+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-18T19:30:38.430+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-19T12:11:41.759+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-19T12:11:41.805+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: fintech_etl_pipeline.run_dashboard manual__2024-12-18T19:03:40.174077+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-02-19T12:11:41.830+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
